name: steam_apps
description: "Steam Apps Project"
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.5.3

dependencies:
    flutter:
        sdk: flutter
    font_awesome_flutter: ^10.2.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/images/
